#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
==============================================================================
  關務單據自動生成器 - Customs Declaration Document Auto-Generator
  上海御大集團 (SHANGHAI YUDA GROUP) 關務系統
==============================================================================

使用說明
--------
本工具讀取「產品主數據庫」與「採購訂單」Excel 檔案，自動生成全套報關單據，
包含商業發票、裝箱單、提單資訊、原產地證申請、申報要素表及核對清單。

執行方式：
    python3 關務單據自動生成器.py

自訂輸入路徑：
    python3 關務單據自動生成器.py \
        --product  /path/to/產品主數據庫.xlsx \
        --po       /path/to/採購訂單.xlsx \
        --output   /path/to/output_dir/

依賴套件：
    pip install openpyxl

輸出：
    單一 Excel 工作簿，包含 6 個 Sheet：
      1. 商業發票 Commercial Invoice
      2. 裝箱單 Packing List
      3. 提單資訊 B/L Info
      4. 原產地證 C/O Application
      5. 申報要素 Declaration Elements
      6. 核對清單 Checklist

作者：QoderWork AI
日期：2026-06-16
==============================================================================
"""

import argparse
import logging
import os
import sys
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

import openpyxl
from openpyxl.styles import (
    Alignment,
    Border,
    Font,
    PatternFill,
    Side,
    numbers,
)
from openpyxl.utils import get_column_letter

# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
COMPANY_NAME = "SHANGHAI YUDA GROUP"
COMPANY_CN = "上海御大集團"
SELLER_NAME = "上海御大國際貿易有限公司"
SELLER_ADDR = (
    "Room 1208, Building A, No. 1888 Zhangheng Road, "
    "Pudong New Area, Shanghai 201203, China"
)
SELLER_CN_ADDR = "上海市浦東新區張衡路1888號A座1208室，郵編201203"

# Color palette
CLR_DEEP_BLUE = "1F4E79"
CLR_WHITE = "FFFFFF"
CLR_LIGHT_GRAY = "F2F2F2"
CLR_MED_GRAY = "D9D9D9"
CLR_FOOTER = "808080"
CLR_HEADER_ROW_ALT = "D6E4F0"

# Reusable style objects
THIN_SIDE = Side(style="thin")
THIN_BORDER = Border(left=THIN_SIDE, right=THIN_SIDE, top=THIN_SIDE, bottom=THIN_SIDE)
MEDIUM_SIDE = Side(style="medium")
MEDIUM_BORDER = Border(left=MEDIUM_SIDE, right=MEDIUM_SIDE, top=MEDIUM_SIDE, bottom=MEDIUM_SIDE)

FONT_TITLE = Font(name="Arial", size=18, bold=True, color=CLR_DEEP_BLUE)
FONT_SUBTITLE = Font(name="Arial", size=14, bold=True, color=CLR_DEEP_BLUE)
FONT_SECTION = Font(name="Arial", size=12, bold=True, color=CLR_DEEP_BLUE)
FONT_INFO_KEY = Font(name="Arial", size=10, bold=True)
FONT_INFO_VAL = Font(name="Arial", size=10)
FONT_TABLE_HDR = Font(name="Arial", size=10, bold=True, color=CLR_WHITE)
FONT_TABLE_CELL = Font(name="Arial", size=10)
FONT_TABLE_CELL_BOLD = Font(name="Arial", size=10, bold=True)
FONT_FOOTER = Font(name="Arial", size=8, italic=True, color=CLR_FOOTER)
FONT_SIGN_LABEL = Font(name="Arial", size=9, color=CLR_FOOTER)

FILL_INFO = PatternFill(start_color=CLR_LIGHT_GRAY, end_color=CLR_LIGHT_GRAY, fill_type="solid")
FILL_HDR = PatternFill(start_color=CLR_DEEP_BLUE, end_color=CLR_DEEP_BLUE, fill_type="solid")
FILL_ALT_ROW = PatternFill(start_color=CLR_HEADER_ROW_ALT, end_color=CLR_HEADER_ROW_ALT, fill_type="solid")
FILL_WHITE = PatternFill(start_color=CLR_WHITE, end_color=CLR_WHITE, fill_type="solid")

ALIGN_CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
ALIGN_LEFT = Alignment(horizontal="left", vertical="center", wrap_text=True)
ALIGN_RIGHT = Alignment(horizontal="right", vertical="center", wrap_text=True)

FOOTER_TEXT = "Generated by QoderWork AI - 上海御大集團關務系統"

# Default file paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_PRODUCT_PATH = os.path.join(BASE_DIR, "產品主數據庫_Product_Master.xlsx")
DEFAULT_PO_PATH = os.path.join(BASE_DIR, "範例採購訂單_Sample_PO.xlsx")
DEFAULT_OUTPUT_DIR = os.path.join(BASE_DIR, "輸出")


# ============================================================================
# Data loading helpers
# ============================================================================

class DataLoader:
    """Reads Product Master and Purchase Order Excel files."""

    @staticmethod
    def load_product_master(filepath: str) -> Dict[str, Dict[str, Any]]:
        """Return dict keyed by product code."""
        logger.info("Loading product master: %s", filepath)
        if not os.path.isfile(filepath):
            raise FileNotFoundError(f"Product master not found: {filepath}")
        wb = openpyxl.load_workbook(filepath, data_only=True)
        ws = wb["Product Master"]
        headers = [cell.value for cell in ws[1]]
        products: Dict[str, Dict[str, Any]] = {}
        for row in ws.iter_rows(min_row=2, values_only=True):
            rec = dict(zip(headers, row))
            code = rec.get("產品內部編碼")
            if code:
                products[code] = rec
        wb.close()
        logger.info("Loaded %d products", len(products))
        return products

    @staticmethod
    def load_purchase_order(filepath: str) -> Tuple[Dict[str, str], List[Dict[str, Any]]]:
        """Return (header_info, detail_items).

        Supports multiple PO layouts:
          - Simple two-column key-value (A:B) in the header area
          - Multi-column layout where keys and values may appear in any column
        Keys are matched by prefix so that '訂單編號 Order No.:' still maps to '訂單編號'.
        """
        logger.info("Loading purchase order: %s", filepath)
        if not os.path.isfile(filepath):
            raise FileNotFoundError(f"Purchase order not found: {filepath}")
        wb = openpyxl.load_workbook(filepath, data_only=True)
        ws = wb["採購訂單"]

        # Canonical key mapping (prefix -> standard key name)
        KEY_MAP = {
            "訂單編號": "訂單編號",
            "訂單日期": "訂單日期",
            "客戶名稱": "客戶名稱",
            "客戶地址": "客戶地址",
            "目的港": "目的港",
            "貿易條款": "貿易條款",
            "付款方式": "付款方式",
            "合同編號": "合同編號",
            "預計出貨": "預計出貨日",
            "備註": "備註",
        }

        def _normalize_key(raw_key: str) -> Optional[str]:
            """Match a raw cell value to a canonical header key."""
            if not raw_key:
                return None
            raw_key = str(raw_key).strip()
            for prefix, canonical in KEY_MAP.items():
                if raw_key.startswith(prefix):
                    return canonical
            return None

        # Find detail header row first (look for '序號' in column A)
        detail_hdr_row = None
        for row in range(1, ws.max_row + 1):
            cell_val = ws.cell(row=row, column=1).value
            if cell_val is not None and str(cell_val).strip() == "序號":
                detail_hdr_row = row
                break
        if detail_hdr_row is None:
            raise ValueError("Cannot find detail header row (序號) in PO")

        # --- Parse header (all rows above detail header) ---
        header: Dict[str, str] = {}
        for row in range(1, detail_hdr_row):
            for col in range(1, ws.max_column + 1):
                raw = ws.cell(row=row, column=col).value
                canon = _normalize_key(raw)
                if canon is None:
                    continue
                # Value is the next non-empty cell to the right
                val = None
                for vc in range(col + 1, ws.max_column + 1):
                    candidate = ws.cell(row=row, column=vc).value
                    # skip if this candidate is itself a key
                    if candidate and _normalize_key(str(candidate)) is not None:
                        break
                    if candidate is not None and str(candidate).strip() != "":
                        val = candidate
                        break
                header[canon] = str(val).strip() if val else ""

        logger.info("PO header parsed: %s", {k: v for k, v in header.items() if v})

        # --- Parse detail items ---
        raw_headers = [ws.cell(row=detail_hdr_row, column=c).value for c in range(1, ws.max_column + 1)]
        # Normalize column names
        COL_ALIAS = {
            "產品編碼": "產品內部編碼",
            "型號": "型號規格",
        }
        detail_headers = []
        for h in raw_headers:
            h_str = str(h).strip() if h else ""
            detail_headers.append(COL_ALIAS.get(h_str, h_str))

        items: List[Dict[str, Any]] = []
        for row in range(detail_hdr_row + 1, ws.max_row + 1):
            vals = [ws.cell(row=row, column=c).value for c in range(1, ws.max_column + 1)]
            if all(v is None for v in vals):
                continue
            rec = dict(zip(detail_headers, vals))
            seq = rec.get("序號")
            if seq is not None and str(seq).strip().isdigit():
                # Cast numeric fields
                for nf in ("數量", "單價USD", "金額USD"):
                    if rec.get(nf) is not None:
                        try:
                            rec[nf] = float(rec[nf])
                        except (ValueError, TypeError):
                            pass
                items.append(rec)
        wb.close()
        logger.info("PO header: %s | Items: %d", header.get("訂單編號", "N/A"), len(items))
        return header, items


# ============================================================================
# Merged cell helper
# ============================================================================

def merge_and_write(ws, row: int, col_start: int, col_end: int,
                    value: Any, font: Font = FONT_INFO_VAL,
                    alignment: Alignment = ALIGN_LEFT,
                    fill: Optional[PatternFill] = None,
                    border: Optional[Border] = None):
    """Merge cells horizontally and write a value."""
    ws.merge_cells(start_row=row, start_column=col_start,
                   end_row=row, end_column=col_end)
    cell = ws.cell(row=row, column=col_start, value=value)
    cell.font = font
    cell.alignment = alignment
    if fill:
        cell.fill = fill
    if border:
        # Apply border to all cells in merge range
        for c in range(col_start, col_end + 1):
            ws.cell(row=row, column=c).border = border
    return cell


def set_row_border(ws, row: int, col_start: int, col_end: int,
                   border: Border = THIN_BORDER):
    for c in range(col_start, col_end + 1):
        ws.cell(row=row, column=c).border = border


# ============================================================================
# Document Generators
# ============================================================================

class DocumentGenerator:
    """Base class with common helpers for all document sheets."""

    def __init__(self, ws, po_header: Dict[str, str],
                 po_items: List[Dict[str, Any]],
                 products: Dict[str, Dict[str, Any]]):
        self.ws = ws
        self.po = po_header
        self.items = po_items
        self.products = products
        self.current_row = 1
        self.max_col = 10  # default, overridden by subclasses

    # -- Common builders ---------------------------------------------------

    def _write_company_header(self, title_cn: str, title_en: str, subtitle: str = ""):
        """Write company name + document title."""
        merge_and_write(self.ws, self.current_row, 1, self.max_col,
                        COMPANY_NAME, FONT_TITLE, ALIGN_CENTER)
        self.current_row += 1
        merge_and_write(self.ws, self.current_row, 1, self.max_col,
                        f"{title_cn} / {title_en}", FONT_SUBTITLE, ALIGN_CENTER)
        self.current_row += 1
        if subtitle:
            merge_and_write(self.ws, self.current_row, 1, self.max_col,
                            subtitle, FONT_SECTION, ALIGN_CENTER)
            self.current_row += 1
        self.current_row += 1  # blank row

    def _write_info_block(self, pairs: List[Tuple[str, str]], fill: PatternFill = FILL_INFO):
        """Write key-value info block spanning two columns each."""
        half = self.max_col // 2
        for i in range(0, len(pairs), 2):
            # Left pair
            k1, v1 = pairs[i]
            merge_and_write(self.ws, self.current_row, 1, 2, k1, FONT_INFO_KEY,
                            ALIGN_LEFT, fill, THIN_BORDER)
            merge_and_write(self.ws, self.current_row, 3, half, v1, FONT_INFO_VAL,
                            ALIGN_LEFT, fill, THIN_BORDER)
            # Right pair if available
            if i + 1 < len(pairs):
                k2, v2 = pairs[i + 1]
                merge_and_write(self.ws, self.current_row, half + 1, half + 2, k2,
                                FONT_INFO_KEY, ALIGN_LEFT, fill, THIN_BORDER)
                merge_and_write(self.ws, self.current_row, half + 3, self.max_col, v2,
                                FONT_INFO_VAL, ALIGN_LEFT, fill, THIN_BORDER)
            else:
                merge_and_write(self.ws, self.current_row, half + 1, self.max_col,
                                "", FONT_INFO_VAL, ALIGN_LEFT, fill, THIN_BORDER)
            self.current_row += 1

    def _write_table_header(self, headers: List[str]):
        for col_idx, h in enumerate(headers, 1):
            cell = self.ws.cell(row=self.current_row, column=col_idx, value=h)
            cell.font = FONT_TABLE_HDR
            cell.fill = FILL_HDR
            cell.alignment = ALIGN_CENTER
            cell.border = THIN_BORDER
        self.current_row += 1

    def _write_table_row(self, values: List[Any], bold_last: bool = False,
                         number_fmt_cols: Optional[List[int]] = None,
                         alt: bool = False):
        fill = FILL_ALT_ROW if alt else FILL_WHITE
        for col_idx, val in enumerate(values, 1):
            cell = self.ws.cell(row=self.current_row, column=col_idx, value=val)
            cell.font = FONT_TABLE_CELL_BOLD if (bold_last and col_idx == len(values)) else FONT_TABLE_CELL
            cell.border = THIN_BORDER
            cell.alignment = ALIGN_CENTER
            if fill:
                cell.fill = fill
            if number_fmt_cols and col_idx in number_fmt_cols:
                cell.number_format = '#,##0.00'
        self.current_row += 1

    def _write_total_row(self, values: List[Any], number_fmt_cols: Optional[List[int]] = None):
        for col_idx, val in enumerate(values, 1):
            cell = self.ws.cell(row=self.current_row, column=col_idx, value=val)
            cell.font = FONT_TABLE_CELL_BOLD
            cell.border = MEDIUM_BORDER
            cell.alignment = ALIGN_CENTER
            cell.fill = PatternFill(start_color=CLR_MED_GRAY, end_color=CLR_MED_GRAY, fill_type="solid")
            if number_fmt_cols and col_idx in number_fmt_cols:
                cell.number_format = '#,##0.00'
        self.current_row += 1

    def _write_footer(self):
        self.current_row += 1
        merge_and_write(self.ws, self.current_row, 1, self.max_col,
                        FOOTER_TEXT, FONT_FOOTER, ALIGN_CENTER)

    def _write_signature_block(self, labels: Optional[List[str]] = None):
        if labels is None:
            labels = ["Prepared by / 製表人", "Checked by / 核對人", "Approved by / 批准人"]
        self.current_row += 2
        col_span = self.max_col // len(labels)
        for i, label in enumerate(labels):
            start_col = i * col_span + 1
            end_col = start_col + col_span - 1
            merge_and_write(self.ws, self.current_row, start_col, end_col,
                            label, FONT_SIGN_LABEL, ALIGN_CENTER)
        self.current_row += 1
        for i in range(len(labels)):
            start_col = i * col_span + 1
            end_col = start_col + col_span - 1
            merge_and_write(self.ws, self.current_row, start_col, end_col,
                            "Signature / 簽名: ________________", FONT_SIGN_LABEL, ALIGN_LEFT)
        self.current_row += 1
        merge_and_write(self.ws, self.current_row, 1, self.max_col,
                        f"Date / 日期: ________________", FONT_SIGN_LABEL, ALIGN_RIGHT)

    def _set_column_widths(self, widths: Dict[int, float]):
        for col_idx, w in widths.items():
            self.ws.column_dimensions[get_column_letter(col_idx)].width = w

    def _enrich_items(self) -> List[Dict[str, Any]]:
        """Merge PO items with product master data."""
        enriched = []
        for item in self.items:
            code = item.get("產品內部編碼", "")
            prod = self.products.get(code, {})
            merged = {**prod, **{k: v for k, v in item.items() if v is not None}}
            enriched.append(merged)
        return enriched

    # -- Abstract-like method -----------------------------------------------
    def generate(self):
        raise NotImplementedError


# ============================================================================
# Sheet 1: Commercial Invoice
# ============================================================================

class CommercialInvoiceGenerator(DocumentGenerator):

    def __init__(self, ws, po_header, po_items, products):
        super().__init__(ws, po_header, po_items, products)
        self.max_col = 10

    def generate(self):
        logger.info("Generating Commercial Invoice ...")
        enriched = self._enrich_items()
        invoice_no = f"CI-{self.po.get('訂單編號', 'XXXX')}"
        po_date = self.po.get("訂單日期", datetime.now().strftime("%Y-%m-%d"))
        buyer = self.po.get("客戶名稱", "")
        buyer_addr = self.po.get("客戶地址", "")
        dest_port = self.po.get("目的港", "")
        trade_terms = self.po.get("貿易條款", "")
        payment = self.po.get("付款方式", "")
        contract_no = self.po.get("合同編號", "")

        # Title
        self._write_company_header(
            "商業發票", "COMMERCIAL INVOICE",
            f"Invoice No. / 發票號碼: {invoice_no}"
        )

        # Info block
        self._write_info_block([
            ("Invoice No. / 發票號碼", invoice_no),
            ("Date / 日期", po_date),
            ("Seller / 賣方", SELLER_NAME),
            ("Buyer / 買方", buyer),
            ("Address / 地址", SELLER_CN_ADDR),
            ("Buyer Address / 買方地址", buyer_addr),
            ("Contract No. / 合同編號", contract_no),
            ("Trade Terms / 貿易條款", trade_terms),
        ])
        self.current_row += 1

        # Shipping info
        self._write_info_block([
            ("From / 起運港", "Shanghai, China"),
            ("To / 目的港", dest_port),
            ("Shipping Marks / 嘜頭", f"N/M - {buyer[:20]}" if buyer else "N/M"),
            ("Payment / 付款方式", payment),
        ])
        self.current_row += 1

        # Detail table
        headers = [
            "Item No.\n項號", "Description of Goods (English)\n貨物描述（英文）",
            "Model\n型號", "HS Code\nHS編碼", "Quantity\n數量",
            "Unit\n單位", "Unit Price\n(USD)\n單價", "Amount\n(USD)\n金額",
            "Country of\nOrigin\n原產地", "Remarks\n備註"
        ]
        self._write_table_header(headers)

        total_qty = 0
        total_amount = 0.0
        for idx, item in enumerate(enriched):
            qty = item.get("數量", 0) or 0
            unit_price = item.get("單價USD", 0) or 0
            amount = qty * unit_price
            total_qty += qty
            total_amount += amount
            self._write_table_row(
                [
                    idx + 1,
                    item.get("英文品名", ""),
                    item.get("型號規格", ""),
                    item.get("HS編碼", ""),
                    qty,
                    item.get("單位", ""),
                    unit_price,
                    amount,
                    item.get("原產地", "China"),
                    item.get("備註", ""),
                ],
                number_fmt_cols=[7, 8],
                alt=(idx % 2 == 1),
            )

        # Totals
        self._write_total_row(
            ["", "TOTAL / 合計", "", "", total_qty, "", "", total_amount, "", ""],
            number_fmt_cols=[8],
        )
        self.current_row += 1

        # Summary block
        self._write_info_block([
            ("Total Quantity / 總數量", f"{total_qty}"),
            ("Total Amount / 總金額", f"USD {total_amount:,.2f}"),
            ("Trade Terms / 貿易條款", trade_terms),
            ("Payment Terms / 付款條件", payment),
        ])

        # Amount in words
        self.current_row += 1
        merge_and_write(self.ws, self.current_row, 1, self.max_col,
                        f"Say Total / 金額大寫: US DOLLARS {self._amount_to_words(total_amount)} ONLY",
                        FONT_INFO_KEY, ALIGN_LEFT, FILL_INFO, THIN_BORDER)

        self._write_signature_block()
        self._write_footer()
        self._set_column_widths({1: 8, 2: 32, 3: 16, 4: 16, 5: 10, 6: 8, 7: 14, 8: 16, 9: 12, 10: 18})

    @staticmethod
    def _amount_to_words(amount: float) -> str:
        """Simplified amount-to-words for USD."""
        whole = int(amount)
        cents = round((amount - whole) * 100)
        return f"{whole:,} AND CENTS {cents:02d}"


# ============================================================================
# Sheet 2: Packing List
# ============================================================================

class PackingListGenerator(DocumentGenerator):

    def __init__(self, ws, po_header, po_items, products):
        super().__init__(ws, po_header, po_items, products)
        self.max_col = 10

    def generate(self):
        logger.info("Generating Packing List ...")
        enriched = self._enrich_items()
        invoice_no = f"CI-{self.po.get('訂單編號', 'XXXX')}"
        po_date = self.po.get("訂單日期", "")
        buyer = self.po.get("客戶名稱", "")
        buyer_addr = self.po.get("客戶地址", "")
        dest_port = self.po.get("目的港", "")

        self._write_company_header("裝箱單", "PACKING LIST")

        self._write_info_block([
            ("Invoice No. / 發票號碼", invoice_no),
            ("Date / 日期", po_date),
            ("Seller / 賣方", SELLER_NAME),
            ("Buyer / 買方", buyer),
            ("From / 起運港", "Shanghai, China"),
            ("To / 目的港", dest_port),
            ("Shipping Marks / 嘜頭", f"N/M - {buyer[:20]}" if buyer else "N/M"),
            ("Contract No. / 合同編號", self.po.get("合同編號", "")),
        ])
        self.current_row += 1

        # Table
        headers = [
            "Item No.\n項號", "Description\n貨物描述", "Model\n型號",
            "Quantity\n數量", "Packages\n件數", "Net Weight\n(kg)\n淨重",
            "Gross Weight\n(kg)\n毛重", "Measurement\n(cm)\n尺寸",
            "CBM\n(m³)\n體積", "Remarks\n備註"
        ]
        self._write_table_header(headers)

        total_qty = 0
        total_pkg = 0
        total_nw = 0.0
        total_gw = 0.0
        total_cbm = 0.0

        for idx, item in enumerate(enriched):
            qty = item.get("數量", 0) or 0
            nw_unit = item.get("淨重kg", 0) or 0
            gw_unit = item.get("毛重kg", 0) or 0
            length = item.get("長cm", 0) or 0
            width = item.get("寬cm", 0) or 0
            height = item.get("高cm", 0) or 0

            total_nw_item = nw_unit * qty
            total_gw_item = gw_unit * qty
            # Estimate packages: 1 package per 50 pcs (or at least 1)
            packages = max(1, qty // 50) if qty >= 50 else (1 if qty > 0 else 0)
            # CBM per item = L*W*H/1000000 * packages (assuming carton dims = unit dims * packing factor)
            cbm_item = (length * width * height / 1_000_000) * packages

            total_qty += qty
            total_pkg += packages
            total_nw += total_nw_item
            total_gw += total_gw_item
            total_cbm += cbm_item

            meas_str = f"{length}x{width}x{height}"

            self._write_table_row(
                [
                    idx + 1, item.get("英文品名", ""), item.get("型號規格", ""),
                    qty, packages, round(total_nw_item, 2), round(total_gw_item, 2),
                    meas_str, round(cbm_item, 4), item.get("備註", ""),
                ],
                number_fmt_cols=[6, 7, 9],
                alt=(idx % 2 == 1),
            )

        self._write_total_row(
            ["", "TOTAL / 合計", "", total_qty, total_pkg,
             round(total_nw, 2), round(total_gw, 2), "",
             round(total_cbm, 4), ""],
            number_fmt_cols=[6, 7, 9],
        )

        self.current_row += 1
        self._write_info_block([
            ("Total Packages / 總件數", f"{total_pkg}"),
            ("Total Net Weight / 總淨重", f"{total_nw:,.2f} kg"),
            ("Total Gross Weight / 總毛重", f"{total_gw:,.2f} kg"),
            ("Total CBM / 總體積", f"{total_cbm:,.4f} m³"),
        ])

        self._write_signature_block()
        self._write_footer()
        self._set_column_widths({1: 8, 2: 30, 3: 16, 4: 10, 5: 10, 6: 14, 7: 14, 8: 18, 9: 12, 10: 18})


# ============================================================================
# Sheet 3: B/L Information
# ============================================================================

class BillOfLadingGenerator(DocumentGenerator):

    def __init__(self, ws, po_header, po_items, products):
        super().__init__(ws, po_header, po_items, products)
        self.max_col = 8

    def generate(self):
        logger.info("Generating B/L Information ...")
        enriched = self._enrich_items()
        buyer = self.po.get("客戶名稱", "")
        buyer_addr = self.po.get("客戶地址", "")
        dest_port = self.po.get("目的港", "")
        trade_terms = self.po.get("貿易條款", "").upper()
        invoice_no = f"CI-{self.po.get('訂單編號', 'XXXX')}"

        self._write_company_header("提單資訊", "BILL OF LADING INFORMATION")

        # Determine freight prepaid or collect
        freight = "PREPAID" if any(t in trade_terms for t in ["CIF", "CFR", "CIP", "CPT", "DAP", "DDP", "DAT"]) else "COLLECT"

        # Parties
        self._write_info_block([
            ("Shipper / 託運人", SELLER_NAME),
            ("Consignee / 收貨人", buyer),
            ("Address / 地址", SELLER_CN_ADDR),
            ("Address / 地址", buyer_addr),
            ("Notify Party / 通知方", buyer),
            ("Notify Address / 通知地址", buyer_addr),
        ])
        self.current_row += 1

        # Vessel & ports
        self._write_info_block([
            ("Vessel / 船名", "TO BE NOMINATED / 待定"),
            ("Voyage / 航次", "TO BE NOMINATED / 待定"),
            ("Port of Loading / 裝貨港", "Shanghai, China"),
            ("Port of Discharge / 卸貨港", dest_port),
            ("Place of Receipt / 收貨地", "Shanghai, China"),
            ("Place of Delivery / 交貨地", dest_port),
            ("B/L No. / 提單號", "TO BE ASSIGNED / 待分配"),
            ("Freight / 運費", freight),
        ])
        self.current_row += 1

        # Cargo description table
        headers = [
            "Marks & Numbers\n嘜頭", "Description of Goods\n貨物描述",
            "Quantity\n數量", "Unit\n單位",
            "Net Weight (kg)\n淨重", "Gross Weight (kg)\n毛重",
            "Measurement (cm)\n尺寸", "CBM (m³)\n體積"
        ]
        self._write_table_header(headers)

        total_qty = 0
        total_nw = 0.0
        total_gw = 0.0
        total_cbm = 0.0
        marks = f"N/M\n{invoice_no}\n{dest_port}"

        for idx, item in enumerate(enriched):
            qty = item.get("數量", 0) or 0
            nw_unit = item.get("淨重kg", 0) or 0
            gw_unit = item.get("毛重kg", 0) or 0
            l = item.get("長cm", 0) or 0
            w = item.get("寬cm", 0) or 0
            h = item.get("高cm", 0) or 0
            packages = max(1, qty // 50) if qty >= 50 else (1 if qty > 0 else 0)
            cbm = (l * w * h / 1_000_000) * packages

            total_qty += qty
            total_nw += nw_unit * qty
            total_gw += gw_unit * qty
            total_cbm += cbm

            self._write_table_row(
                [
                    marks if idx == 0 else "",
                    item.get("英文品名", ""),
                    qty, item.get("單位", ""),
                    round(nw_unit * qty, 2), round(gw_unit * qty, 2),
                    f"{l}x{w}x{h}", round(cbm, 4),
                ],
                number_fmt_cols=[5, 6, 8],
                alt=(idx % 2 == 1),
            )

        self._write_total_row(
            ["", "TOTAL", total_qty, "",
             round(total_nw, 2), round(total_gw, 2), "", round(total_cbm, 4)],
            number_fmt_cols=[5, 6, 8],
        )

        self.current_row += 1
        self._write_info_block([
            ("Freight / 運費", freight),
            ("Number of Original B/L / 正本提單份數", "THREE (3)"),
            ("Number of Copies / 副本份數", "THREE (3)"),
            ("Remarks / 備註", ""),
        ])

        self._write_signature_block(["Prepared by / 製表人", "Confirmed by / 確認人"])
        self._write_footer()
        self._set_column_widths({1: 18, 2: 32, 3: 10, 4: 8, 5: 14, 6: 14, 7: 18, 8: 12})


# ============================================================================
# Sheet 4: Certificate of Origin Application
# ============================================================================

class CertificateOfOriginGenerator(DocumentGenerator):

    def __init__(self, ws, po_header, po_items, products):
        super().__init__(ws, po_header, po_items, products)
        self.max_col = 8

    def generate(self):
        logger.info("Generating C/O Application ...")
        enriched = self._enrich_items()
        buyer = self.po.get("客戶名稱", "")
        buyer_addr = self.po.get("客戶地址", "")
        dest_port = self.po.get("目的港", "")
        po_date = self.po.get("訂單日期", "")
        invoice_no = f"CI-{self.po.get('訂單編號', 'XXXX')}"

        self._write_company_header(
            "原產地證申請", "CERTIFICATE OF ORIGIN APPLICATION",
            "FORM E / 中國-東盟自由貿易區原產地證書"
        )

        self._write_info_block([
            ("Exporter / 出口商", SELLER_NAME),
            ("Consignee / 收貨人", buyer),
            ("Address / 地址", SELLER_CN_ADDR),
            ("Address / 地址", buyer_addr),
            ("Transport Details / 運輸詳情", "FROM SHANGHAI, CHINA TO " + dest_port.upper()),
            ("Invoice No. / 發票號碼", invoice_no),
            ("Date / 日期", po_date),
            ("Country of Origin / 原產國", "PEOPLE'S REPUBLIC OF CHINA"),
        ])
        self.current_row += 1

        # Goods table
        headers = [
            "Item No.\n項號", "Description of Goods\n貨物描述",
            "HS Code\nHS編碼", "Origin Criterion\n原產地標準",
            "Quantity\n數量", "Unit\n單位",
            "FOB Value (USD)\nFOB價值", "Country of Origin\n原產國"
        ]
        self._write_table_header(headers)

        total_fob = 0.0
        for idx, item in enumerate(enriched):
            qty = item.get("數量", 0) or 0
            unit_price = item.get("單價USD", 0) or 0
            fob_val = qty * unit_price
            total_fob += fob_val

            # Origin criterion: WO = wholly obtained, PS = substantially processed
            hs = str(item.get("HS編碼", ""))
            criterion = "WO" if hs.startswith(("73", "74", "75", "76")) else "PS"

            self._write_table_row(
                [
                    idx + 1, item.get("英文品名", ""),
                    hs, criterion,
                    qty, item.get("單位", ""),
                    fob_val, "China",
                ],
                number_fmt_cols=[7],
                alt=(idx % 2 == 1),
            )

        self._write_total_row(
            ["", "TOTAL", "", "", "", "", total_fob, ""],
            number_fmt_cols=[7],
        )

        # Declaration section
        self.current_row += 2
        merge_and_write(self.ws, self.current_row, 1, self.max_col,
                        "DECLARATION / 原產地聲明", FONT_SECTION, ALIGN_LEFT, FILL_INFO, THIN_BORDER)
        self.current_row += 1
        declarations = [
            "1. The undersigned hereby declares that the goods described above comply with the origin criteria specified in the relevant Free Trade Agreement.",
            "   本人聲明上述貨物符合相關自由貿易協定規定的原產地標準。",
            "2. All information provided in this application is true and accurate.",
            "   本申請表中所填的一切信息均屬真實準確。",
            "3. The goods are of Chinese origin and were wholly obtained / substantially processed in China.",
            "   該貨物為中國原產，在中國完全獲得 / 實質性加工。",
        ]
        for line in declarations:
            merge_and_write(self.ws, self.current_row, 1, self.max_col,
                            line, FONT_INFO_VAL, ALIGN_LEFT)
            self.current_row += 1

        self._write_signature_block(["Applicant / 申請人", "Authorized by / 授權人"])
        self._write_footer()
        self._set_column_widths({1: 8, 2: 32, 3: 16, 4: 16, 5: 10, 6: 8, 7: 16, 8: 14})


# ============================================================================
# Sheet 5: Declaration Elements
# ============================================================================

class DeclarationElementsGenerator(DocumentGenerator):

    def __init__(self, ws, po_header, po_items, products):
        super().__init__(ws, po_header, po_items, products)
        self.max_col = 9

    def generate(self):
        logger.info("Generating Declaration Elements ...")
        enriched = self._enrich_items()
        invoice_no = f"CI-{self.po.get('訂單編號', 'XXXX')}"
        po_date = self.po.get("訂單日期", "")

        self._write_company_header(
            "海關申報要素表", "CUSTOMS DECLARATION ELEMENTS",
            f"Invoice No. / 發票號碼: {invoice_no}  |  Date / 日期: {po_date}"
        )

        self._write_info_block([
            ("訂單編號", self.po.get("訂單編號", "")),
            ("合同編號", self.po.get("合同編號", "")),
            ("客戶名稱", self.po.get("客戶名稱", "")),
            ("目的港", self.po.get("目的港", "")),
        ])
        self.current_row += 1

        for idx, item in enumerate(enriched):
            # Product sub-header
            merge_and_write(self.ws, self.current_row, 1, self.max_col,
                            f"Product #{idx + 1}: {item.get('中文品名', '')} / {item.get('英文品名', '')}",
                            FONT_SECTION, ALIGN_LEFT, FILL_INFO, THIN_BORDER)
            self.current_row += 1

            # Basic info row
            basic_headers = ["產品編碼", "HS編碼", "型號規格", "品牌", "單位", "數量", "單價USD", "原產地"]
            basic_values = [
                item.get("產品內部編碼", ""),
                item.get("HS編碼", ""),
                item.get("型號規格", ""),
                item.get("品牌", ""),
                item.get("單位", ""),
                item.get("數量", ""),
                item.get("單價USD", ""),
                item.get("原產地", ""),
            ]
            for ci, h in enumerate(basic_headers, 1):
                cell_k = self.ws.cell(row=self.current_row, column=ci, value=h)
                cell_k.font = FONT_INFO_KEY
                cell_k.fill = PatternFill(start_color=CLR_MED_GRAY, end_color=CLR_MED_GRAY, fill_type="solid")
                cell_k.alignment = ALIGN_CENTER
                cell_k.border = THIN_BORDER
            self.current_row += 1
            for ci, v in enumerate(basic_values, 1):
                cell_v = self.ws.cell(row=self.current_row, column=ci, value=v)
                cell_v.font = FONT_TABLE_CELL
                cell_v.alignment = ALIGN_CENTER
                cell_v.border = THIN_BORDER
                if ci == 7 and isinstance(v, (int, float)):
                    cell_v.number_format = '#,##0.00'
            self.current_row += 1

            # Declaration elements detail
            elem_headers = ["申報要素項目", "中文內容", "英文內容"]
            merge_and_write(self.ws, self.current_row, 1, 3, elem_headers[0],
                            FONT_TABLE_HDR, ALIGN_CENTER, FILL_HDR, THIN_BORDER)
            merge_and_write(self.ws, self.current_row, 4, 6, elem_headers[1],
                            FONT_TABLE_HDR, ALIGN_CENTER, FILL_HDR, THIN_BORDER)
            merge_and_write(self.ws, self.current_row, 7, self.max_col, elem_headers[2],
                            FONT_TABLE_HDR, ALIGN_CENTER, FILL_HDR, THIN_BORDER)
            self.current_row += 1

            elements_cn = self._parse_declaration(item.get("申報要素描述_中文", ""))
            elements_en = self._parse_declaration(item.get("申報要素描述_英文", ""))

            all_keys = list(dict.fromkeys(list(elements_cn.keys()) + list(elements_en.keys())))

            for alt_idx, key in enumerate(all_keys):
                cn_val = elements_cn.get(key, "")
                en_val = elements_en.get(key, "")
                # Element name spans cols 1-3
                merge_and_write(self.ws, self.current_row, 1, 3,
                                key, FONT_TABLE_CELL_BOLD, ALIGN_LEFT,
                                FILL_ALT_ROW if alt_idx % 2 else FILL_WHITE, THIN_BORDER)
                merge_and_write(self.ws, self.current_row, 4, 6,
                                cn_val, FONT_TABLE_CELL, ALIGN_LEFT,
                                FILL_ALT_ROW if alt_idx % 2 else FILL_WHITE, THIN_BORDER)
                merge_and_write(self.ws, self.current_row, 7, self.max_col,
                                en_val, FONT_TABLE_CELL, ALIGN_LEFT,
                                FILL_ALT_ROW if alt_idx % 2 else FILL_WHITE, THIN_BORDER)
                self.current_row += 1

            # Additional descriptors
            extra_fields = [
                ("功能描述", item.get("功能描述_中文", ""), item.get("功能描述_英文", "")),
                ("材質", item.get("材質", ""), item.get("材質", "")),
                ("用途", item.get("用途", ""), item.get("用途", "")),
            ]
            for field_name, cn_val, en_val in extra_fields:
                if cn_val or en_val:
                    merge_and_write(self.ws, self.current_row, 1, 3,
                                    field_name, FONT_TABLE_CELL_BOLD, ALIGN_LEFT, FILL_INFO, THIN_BORDER)
                    merge_and_write(self.ws, self.current_row, 4, 6,
                                    cn_val, FONT_TABLE_CELL, ALIGN_LEFT, FILL_INFO, THIN_BORDER)
                    merge_and_write(self.ws, self.current_row, 7, self.max_col,
                                    en_val, FONT_TABLE_CELL, ALIGN_LEFT, FILL_INFO, THIN_BORDER)
                    self.current_row += 1

            self.current_row += 1  # gap between products

        self._write_signature_block(["核對人 / Checker", "審核人 / Reviewer"])
        self._write_footer()
        self._set_column_widths({1: 14, 2: 14, 3: 14, 4: 14, 5: 14, 6: 14, 7: 14, 8: 14, 9: 14})

    @staticmethod
    def _parse_declaration(text: str) -> Dict[str, str]:
        """Parse 'key:value|key:value' declaration string."""
        result = {}
        if not text:
            return result
        for part in text.split("|"):
            part = part.strip()
            if ":" in part:
                k, v = part.split(":", 1)
                result[k.strip()] = v.strip()
        return result


# ============================================================================
# Sheet 6: Checklist
# ============================================================================

class ChecklistGenerator(DocumentGenerator):

    def __init__(self, ws, po_header, po_items, products):
        super().__init__(ws, po_header, po_items, products)
        self.max_col = 6

    def generate(self):
        logger.info("Generating Document Checklist ...")
        invoice_no = f"CI-{self.po.get('訂單編號', 'XXXX')}"

        self._write_company_header(
            "報關資料核對清單", "DOCUMENT CHECKLIST",
            f"訂單編號: {self.po.get('訂單編號', '')}"
        )

        self._write_info_block([
            ("訂單編號", self.po.get("訂單編號", "")),
            ("訂單日期", self.po.get("訂單日期", "")),
            ("合同編號", self.po.get("合同編號", "")),
            ("客戶名稱", self.po.get("客戶名稱", "")),
            ("目的港", self.po.get("目的港", "")),
            ("貿易條款", self.po.get("貿易條款", "")),
        ])
        self.current_row += 1

        # Checklist table
        headers = ["序號\nNo.", "核對項目\nCheck Item", "狀態\nStatus",
                    "備註\nRemarks", "核對人\nChecker", "日期\nDate"]
        self._write_table_header(headers)

        checklist_items = [
            ("商業發票已製作 / Commercial Invoice prepared", "☐"),
            ("裝箱單已製作 / Packing List prepared", "☐"),
            ("提單資訊已確認 / B/L information confirmed", "☐"),
            ("原產地證已申請 / Certificate of Origin applied", "☐"),
            ("申報要素已核對 / Declaration elements verified", "☐"),
            ("HS編碼已確認 / HS Codes confirmed", "☐"),
            ("品牌授權已確認 / Brand authorization confirmed", "☐"),
            ("產品照片已準備 / Product photos prepared", "☐"),
            ("嘜頭已製作 / Shipping marks prepared", "☐"),
            ("合同副本已準備 / Contract copy prepared", "☐"),
            ("報關委託書已簽署 / Customs broker authorization signed", "☐"),
            ("其他 / Others: _______________", "☐"),
        ]

        for idx, (desc, status) in enumerate(checklist_items):
            self._write_table_row(
                [idx + 1, desc, status, "", "", ""],
                alt=(idx % 2 == 1),
            )

        # Additional notes section
        self.current_row += 2
        merge_and_write(self.ws, self.current_row, 1, self.max_col,
                        "特別注意事項 / Special Notes:", FONT_SECTION, ALIGN_LEFT, FILL_INFO, THIN_BORDER)
        self.current_row += 1
        notes = [
            "1. 所有單據必須在貨物出運前 3 個工作日完成核對。",
            "2. HS編碼如有疑問，請聯繫報關行確認。",
            "3. 品牌授權文件需在報關時隨附。",
            "4. 如涉及法檢商品，需提前申請檢驗檢疫。",
            "5. All documents must be verified 3 working days before shipment.",
        ]
        for note in notes:
            merge_and_write(self.ws, self.current_row, 1, self.max_col,
                            note, FONT_INFO_VAL, ALIGN_LEFT)
            self.current_row += 1

        self._write_signature_block(["核對人 / Checker", "主管 / Supervisor"])
        self._write_footer()
        self._set_column_widths({1: 8, 2: 48, 3: 10, 4: 20, 5: 14, 6: 14})


# ============================================================================
# Main orchestrator
# ============================================================================

class CustomsDocumentTool:
    """Orchestrates the full document generation pipeline."""

    def __init__(self, product_path: str, po_path: str, output_dir: str):
        self.product_path = product_path
        self.po_path = po_path
        self.output_dir = output_dir

    def run(self) -> str:
        """Execute the full pipeline and return the output file path."""
        # Load data
        products = DataLoader.load_product_master(self.product_path)
        po_header, po_items = DataLoader.load_purchase_order(self.po_path)

        order_no = po_header.get("訂單編號", "UNKNOWN")
        date_str = datetime.now().strftime("%Y%m%d")
        # Sanitize order number for filesystem
        safe_order = "".join(c if c.isalnum() or c in "-_." else "_" for c in order_no)
        filename = f"報關單據_{safe_order}_{date_str}.xlsx"

        os.makedirs(self.output_dir, exist_ok=True)
        output_path = os.path.join(self.output_dir, filename)

        logger.info("Creating output workbook: %s", output_path)
        wb = openpyxl.Workbook()

        # Remove default sheet
        default_sheet = wb.active
        wb.remove(default_sheet)

        # Define generators with sheet names
        # Note: openpyxl forbids / \ * ? : [ ] in sheet titles
        generators = [
            ("商業發票 Commercial Invoice", CommercialInvoiceGenerator),
            ("裝箱單 Packing List", PackingListGenerator),
            ("提單資訊 BL Info", BillOfLadingGenerator),
            ("原產地證 CO Application", CertificateOfOriginGenerator),
            ("申報要素 Declaration Elements", DeclarationElementsGenerator),
            ("核對清單 Checklist", ChecklistGenerator),
        ]

        for sheet_name, gen_cls in generators:
            ws = wb.create_sheet(title=sheet_name)
            gen = gen_cls(ws, po_header, po_items, products)
            try:
                gen.generate()
                logger.info("  Sheet '%s' generated", sheet_name)
            except Exception as e:
                logger.error("  Sheet '%s' failed: %s", sheet_name, e)
                raise

        # Freeze panes and print setup for each sheet
        for ws in wb.worksheets:
            ws.sheet_properties.pageSetUpPr = openpyxl.worksheet.properties.PageSetupProperties(fitToPage=True)
            ws.page_setup.fitToWidth = 1
            ws.page_setup.fitToHeight = 0
            ws.page_setup.orientation = "portrait"
            ws.page_setup.paperSize = ws.PAPERSIZE_A4

        wb.save(output_path)
        wb.close()
        logger.info("=" * 60)
        logger.info("All documents generated successfully!")
        logger.info("Output: %s", output_path)
        logger.info("=" * 60)
        return output_path


# ============================================================================
# CLI entry point
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="關務單據自動生成器 - Customs Declaration Document Auto-Generator"
    )
    parser.add_argument("--product", default=DEFAULT_PRODUCT_PATH,
                        help="Path to Product Master Excel file")
    parser.add_argument("--po", default=DEFAULT_PO_PATH,
                        help="Path to Purchase Order Excel file")
    parser.add_argument("--output", default=DEFAULT_OUTPUT_DIR,
                        help="Output directory")
    args = parser.parse_args()

    tool = CustomsDocumentTool(args.product, args.po, args.output)
    output_path = tool.run()
    print(f"\n{'='*60}")
    print(f"  Output file: {output_path}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
